defaults:
  - default
  - _self_

name: ensemble

amateur_model: null
alpha: 0.1

llm:
  model: ${path_join:${oc.env:MODEL_PATH},${..model}}
  extra_model: ${path_join:${oc.env:MODEL_PATH},${..amateur_model}}
  spec_decoding_acceptance_method: ${..name}
  ensemble_fn: ${eval:'lambda logits:logits[0] - ${..alpha} * logits[1]'}
  ensemble_target: raw-logits