defaults:
  - default
  - _self_

name: "sd"

draft_model: null
gamma: 5

llm:
  model: ${path_join:${oc.env:MODEL_PATH},${..model}}
  speculative_model: ${path_join:${oc.env:MODEL_PATH},${..draft_model}}
  num_speculative_tokens: ${..gamma}