defaults:
  - default
  - _self_


extra_model: null
lambda: null

llm:
  model: ${path_join:${oc.env:MODEL_PATH},${..model}}
  extra_model: ${path_join:${oc.env:MODEL_PATH},${..extra_model}}
  ensemble_fn: ${eval:'lambda probs,logprobs:((1 - ${..lambda}) * probs[0] + ${..lambda} * probs[1], logprobs[0])'}
  ensemble_target: probs
