defaults:
    - method: null
    - _self_


dataset:
    name: null
    size: null
    use_fewshot: True


test_speed: True
max_prompt_len: -1

save_path: null
seed: 42

hydra:
    run:
        dir: ./results/singlerun/results/${now:%Y-%m-%d}/${now:%H-%M-%S}